services:
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  app:
    env_file: .env
    build:
      context: ./app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    expose:
      - ${BACKEND_PORT}
    depends_on:
      - redis
      - db

  db:
    env_file: .env
    image: postgres:15.4-alpine3.18
    restart: always
    environment:
      - PGPORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
